web:
  build: .
  command: 'bash -c ''bin/hubot -a slack'''
  working_dir: /app/user
  environment:
    PORT: 8080
    MONGOLAB_URI: 'mongodb://mongolab:27017/hubot_branin'
  ports:
    - '8080:8080'
  links:
    - mongolab
  env_file:
    - '.env'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
    MONGOLAB_URI: 'mongodb://mongolab:27017/hubot_branin'
  ports:
    - '8080:8080'
  links:
    - mongolab
  volumes:
    - '.:/app/user'
mongolab:
  image: mongo
